name: Build and Deploy documenation
on:
  push:
    branches:
      - develop
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: enyosolutions-team/vue-awesome-components
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn --frozen-lockfile && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist/
