name: Documenation
on:
  push:
    branches:
      - develop
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
    - name: actions/checkout@v2
      uses: actions/setup-python@v2

    - name: actions/setup-python@v2
      uses: actions/setup-python@v2
      with:
        python-version: '2.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: check
      run: python -h

    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: enyosolutions-team/vue-awesome-components
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn --frozen-lockfile && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist/
